### ISSUE TITLE
&[u8] will be serialized as &[u32]

### ISSUE THREAD

**Issue by TsuITOAR** [jvff/serde-xdr#6]
I want to serialize some opaque, and send a `&[u8]` to `to_bytes` function, but actually serializer treated it as a array of `u8`, and serialize each one separatly.For example 
```
let test = [1_u8, 2, 3, 4, 5];
dbg!(serde_xdr::to_bytes(&test.as_ref())?);
```
will output
```
serde_xdr::to_bytes(&test.as_ref())? = [
    0,
    0,
    0,
    5,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    2,
    0,
    0,
    0,
    3,
    0,
    0,
    0,
    4,
    0,
    0,
    0,
    5,
]
```

**Comment by jvff** [comment]
Hi! Thanks for opening this issue, it made me realize I had accidentally removed the [XDR data type map table](https://github.com/jvff/serde-xdr#data-type-map) from the README some time ago :( I've restored [it](https://github.com/jvff/serde-xdr#data-type-map), so that should help with understanding the issue.

As you can see there, all integers with less than 32-bits (`u8`, `u16`, `u32`, `i8`, `i16`, and `i32`) are represented with 4 bytes, so they have padding bytes when needed. To guarantee that the data is serialized as opaque data, you can either use [`serde_bytes::Bytes`](https://docs.rs/serde_bytes/0.11.5/serde_bytes/struct.Bytes.html) for variable-length byte arrays or the [`serde_xdr::opaque_data::fixed_length`](https://docs.rs/serde-xdr/0.6.0/serde_xdr/opaque_data/fixed_length/index.html) module for fixed-length byte arrays.

So, either:

```
let raw_bytes = [1_u8, 2, 3, 4, 5];
let wrapped_bytes = serde_bytes::Bytes::new(&raw_bytes);
// Variable length opaque data
dbg!(serde_xdr::to_bytes(&wrapped_bytes)?);
```

(Note that the result has 12 bytes, 4 for the length, 5 for the data, and 3 padding bytes for 4-byte alignment).

or

```
let test = [1_u8, 2, 3, 4, 5];
let mut output = Vec::new();
let serializer = serde_xdr::Serializer::new(&mut output);
serde_xdr::opaque_data::fixed_length::serialize(&test, serializer)?;
// Fixed length opaque data
dbg!(output);
```

(Here it has 8 bytes, 5 for the data and 3 padding bytes for 4-byte alignment).

I hope this helps, but let me know if you need more help.

**Comment by TsuITOAR** [comment]
> Hi! Thanks for opening this issue, it made me realize I had accidentally removed the [XDR data type map table](https://github.com/jvff/serde-xdr#data-type-map) from the README some time ago :( I've restored [it](https://github.com/jvff/serde-xdr#data-type-map), so that should help with understanding the issue.
> 
> As you can see there, all integers with less than 32-bits (`u8`, `u16`, `u32`, `i8`, `i16`, and `i32`) are represented with 4 bytes, so they have padding bytes when needed. To guarantee that the data is serialized as opaque data, you can either use [`serde_bytes::Bytes`](https://docs.rs/serde_bytes/0.11.5/serde_bytes/struct.Bytes.html) for variable-length byte arrays or the [`serde_xdr::opaque_data::fixed_length`](https://docs.rs/serde-xdr/0.6.0/serde_xdr/opaque_data/fixed_length/index.html) module for fixed-length byte arrays.
> 
> So, either:
> 
> ```
> let raw_bytes = [1_u8, 2, 3, 4, 5];
> let wrapped_bytes = serde_bytes::Bytes::new(&raw_bytes);
> // Variable length opaque data
> dbg!(serde_xdr::to_bytes(&wrapped_bytes)?);
> ```
> 
> (Note that the result has 12 bytes, 4 for the length, 5 for the data, and 3 padding bytes for 4-byte alignment).
> 
> or
> 
> ```
> let test = [1_u8, 2, 3, 4, 5];
> let mut output = Vec::new();
> let serializer = serde_xdr::Serializer::new(&mut output);
> serde_xdr::opaque_data::fixed_length::serialize(&test, serializer)?;
> // Fixed length opaque data
> dbg!(output);
> ```
> 
> (Here it has 8 bytes, 5 for the data and 3 padding bytes for 4-byte alignment).
> 
> I hope this helps, but let me know if you need more help.

Thanks!
I know that `u8` in xdr is serialized as `u32`, but thought that `[u8]` should be treated as bytes implicitly. I was not familiar with `serialize` trait, and as you suggested, I checked `serde_bytes` and know how `serialize_bytes` works now.
Helps a lot.
